/*
-- Query: select * from recap.request_type_t
LIMIT 0, 1000

-- Date: 2016-05-10 18:04
*/
INSERT INTO `recap`.`REQUEST_TYPE_T` (`REQUEST_TYPE_ID`,`REQUEST_TYPE_CODE`,`REQUEST_TYPE_DESC`) VALUES (1,'HOLD','HOLD');
INSERT INTO `recap`.`REQUEST_TYPE_T` (`REQUEST_TYPE_ID`,`REQUEST_TYPE_CODE`,`REQUEST_TYPE_DESC`) VALUES (2,'RETRIEVAL','RETRIEVAL');
INSERT INTO `recap`.`REQUEST_TYPE_T` (`REQUEST_TYPE_ID`,`REQUEST_TYPE_CODE`,`REQUEST_TYPE_DESC`) VALUES (3,'RECALL','RECALL');
INSERT INTO `recap`.`REQUEST_TYPE_T` (`REQUEST_TYPE_ID`,`REQUEST_TYPE_CODE`,`REQUEST_TYPE_DESC`) VALUES (4,'EDD','EDD');
INSERT INTO `recap`.`REQUEST_TYPE_T` (`REQUEST_TYPE_ID`,`REQUEST_TYPE_CODE`,`REQUEST_TYPE_DESC`) VALUES (5,'BORROW_DIRECT','BORROW_DIRECT');
