

INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (1,'user:create','To create users,assign roles');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (2,'CGD:wirte','To write/edit CGD for own institutions');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (3,'deaccession','To deaccession records for own institution');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (4,'request:place:ownInst','Ability to place request within own institution');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (5,'request:place:allInst','Ability to place request within all institutions');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (6,'request:cancel:ownInst','Ability to cancel request within own institution');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (7,'reports:viewPrint','Ability to view & print reports');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (8,'SCSB:searchExport','Ability to search SCSB and export results');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (9,'barcode:restriction','Barcode will be restricted for this role');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (10,'request:items','Ability to request items from any institution');
INSERT INTO PERMISSIONS_T (PERMISSION_ID,PERMISSION_NAME,PERMISSION_DESCRIPTION) VALUES (11,'request:cancel:allInst','Ability to cancel any request');
