

INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,1);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,2);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,3);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,4);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,5);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,6);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,7);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,8);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,10);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (1,11);

INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,1);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,2);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,3);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,4);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,5);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,6);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,7);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,8);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,10);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (2,11);

INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (3,4);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (3,5);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (3,6);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (3,7);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (3,8);

INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (4,2);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (4,3);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (4,4);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (4,5);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (4,6);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (4,7);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (4,8);


INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,4);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,5);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,6);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,7);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,8);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,9);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,10);
INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (5,11);

INSERT INTO ROLE_PERMISSION_T (ROLE_ID,PERMISSION_ID) VALUES (6,8);