

INSERT INTO USER_T (USER_ID,LOGIN_ID,USER_INSTITUTION,USER_DESCRITPTION) VALUES (1,'superadmin',1,'Admin for all institutions');
INSERT INTO USER_T (USER_ID,LOGIN_ID,USER_INSTITUTION,USER_DESCRITPTION) VALUES (2,'jhon',2,'Admin for CUL institution');
INSERT INTO USER_T (USER_ID,LOGIN_ID,USER_INSTITUTION,USER_DESCRITPTION) VALUES (3,'smith',2,'Search & Request user for CUL');
INSERT INTO USER_T (USER_ID,LOGIN_ID,USER_INSTITUTION,USER_DESCRITPTION) VALUES (4,'danie',2,'Search user for CUL');
INSERT INTO USER_T (USER_ID,LOGIN_ID,USER_INSTITUTION,USER_DESCRITPTION) VALUES (5,'kholi',3,'Admin for NYPL institution');
INSERT INTO USER_T (USER_ID,LOGIN_ID,USER_INSTITUTION,USER_DESCRITPTION) VALUES (6,'rusell',1,'ReCAP User');