
INSERT INTO `recap`.`USER_T` (`USER_ID`,`LOGIN_ID`,`USER_INSTITUTION`,`USER_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`LAST_UPDATED_DATE`,`LAST_UPDATED_BY`) VALUES (2,'john',2,'Admin for CUL institution',now(),'ReCAP',now(),'ReCAP');
INSERT INTO `recap`.`USER_T` (`USER_ID`,`LOGIN_ID`,`USER_INSTITUTION`,`USER_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`LAST_UPDATED_DATE`,`LAST_UPDATED_BY`) VALUES (3,'smith',2,'Search & Request user for CUL',now(),'ReCAP',now(),'ReCAP');
INSERT INTO `recap`.`USER_T` (`USER_ID`,`LOGIN_ID`,`USER_INSTITUTION`,`USER_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`LAST_UPDATED_DATE`,`LAST_UPDATED_BY`) VALUES (4,'danie',2,'Search user for CUL',now(),'ReCAP',now(),'ReCAP');
INSERT INTO `recap`.`USER_T` (`USER_ID`,`LOGIN_ID`,`USER_INSTITUTION`,`USER_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`LAST_UPDATED_DATE`,`LAST_UPDATED_BY`) VALUES (5,'kholi',3,'Admin for NYPL institution',now(),'ReCAP',now(),'ReCAP');
INSERT INTO `recap`.`USER_T` (`USER_ID`,`LOGIN_ID`,`USER_INSTITUTION`,`USER_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`LAST_UPDATED_DATE`,`LAST_UPDATED_BY`) VALUES (6,'russell',1,'ReCAP User',now(),'ReCAP',now(),'ReCAP');
