
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (2,2);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (3,3);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (4,6);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (5,2);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (6,5);
