
DELETE FROM `recap`.`USER_ROLE_T` WHERE `USER_ID` IN (1,2,3,4,5,6);

INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (1,1);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (2,2);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (3,3);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (4,6);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (5,2);
INSERT INTO `recap`.`USER_ROLE_T` (`USER_ID`,`ROLE_ID`) VALUES (6,5);