INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_ID ,REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES (1,"RETRIEVAL_ORDER_PLACED","RETRIEVAL ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_ID ,REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES (2,"RECALL_ORDER_PLACED","RECALL ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_ID ,REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES (3,"EDD_ORDER_PLACED","EDD ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_ID ,REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES (4,"REFILED","REFILED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_ID ,REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES (5,"CANCELED","CANCELED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_ID ,REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES (6,"EXCEPTION","EXCEPTION");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_ID, REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES (7, "PENDING", "PENDING");