INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("EXCEPTION","EXCEPTION");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("RETRIEVAL_ORDER_PLACED","RETRIEVAL ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("RECALLED","RECALLED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("RECALL_RETRIEVAL_ORDER_PLACED","RECALL_RETRIEVAL ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("REFILED","REFILED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("CANCELED","CANCELED");
