DELETE FROM recap.REQUEST_ITEM_T;
DELETE FROM recap.REQUEST_ITEM_STATUS_T;
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("RETRIEVAL_ORDER_PLACED","RETRIEVAL ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("RECALL_ORDER_PLACED","RECALL ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("EDD_ORDER_PLACED","EDD ORDER PLACED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("REFILED","REFILED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("CANCELED","CANCELED");
INSERT INTO recap.REQUEST_ITEM_STATUS_T (REQUEST_STATUS_CODE, REQUEST_STATUS_DESC) VALUES ("EXCEPTION","EXCEPTION");