USE `recap`;

CREATE OR REPLACE VIEW `recap`.`MATCHING_INSTBIB_V` AS
SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(HEADER_VALUE, ',', COUNTER.NUM), ',', -1) AS BIBID, RECORD_NUM AS ID
  FROM REPORT_DATA_T T CROSS JOIN
(
   SELECT A.N + B.N * 10 + 1 NUM
     FROM
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) A
   ,(SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) B
    ORDER BY NUM
) COUNTER
 WHERE COUNTER.NUM <= 1 + (LENGTH(HEADER_VALUE) - LENGTH(REPLACE(HEADER_VALUE, ',', '')))
AND HEADER_NAME IN ('BibId')
ORDER BY RECORD_NUM;