/*
-- Delete Triggers for Transaction Tables
-- Date: 2017-05-30
*/

USE recap;

CREATE TRIGGER BIBLIOGRAPHIC_DEL_TRG AFTER DELETE ON BIBLIOGRAPHIC_T FOR EACH ROW

    INSERT INTO DELETED_RECORDS_T (RECORDS_TABLE, RECORDS_PRIMARY_KEY, DELETED_REPORTED_STATUS, DELETED_DATE, DELETED_BY, RECORDS_LOG)
    VALUES ("BIBLIOGRAPHIC_T",""+ OLD.BIBLIOGRAPHIC_ID ,"Not Reported", NOW(), USER()
      ,CONCAT(OLD.OWNING_INST_ID ,"|", OLD.CREATED_DATE ,"|", OLD.CREATED_BY , "|",OLD.LAST_UPDATED_DATE,"|", OLD.LAST_UPDATED_BY,"|", OLD.OWNING_INST_BIB_ID,"|", OLD.IS_DELETED,"|", OLD.CATALOGING_STATUS));
;


CREATE TRIGGER HOLDINGS_T_ADEL AFTER DELETE ON HOLDINGS_T FOR EACH ROW

    INSERT INTO DELETED_RECORDS_T (RECORDS_TABLE, RECORDS_PRIMARY_KEY, DELETED_REPORTED_STATUS, DELETED_DATE, DELETED_BY, RECORDS_LOG)
    VALUES ("HOLDINGS_T",""+ OLD.HOLDINGS_ID , "Not Reported", NOW(), USER()
      ,CONCAT(OLD.OWNING_INST_ID ,"|", OLD.CREATED_DATE ,"|", OLD.CREATED_BY , "|",OLD.LAST_UPDATED_DATE,"|", OLD.LAST_UPDATED_BY,"|", OLD.OWNING_INST_HOLDINGS_ID,"|", OLD.IS_DELETED));
;

CREATE DEFINER=`recap`@`%` TRIGGER `item_t_ADEL` AFTER DELETE ON `item_t` FOR EACH ROW

    INSERT INTO deleted_records_t (RECORDS_TABLE, RECORDS_PRIMARY_KEY,  DELETED_REPORTED_STATUS, DELETED_DATE, DELETED_BY, RECORDS_LOG)
    VALUES ("item_t",""+ OLD.ITEM_ID  ,"Not Reported", NOW(), USER() ,CONCAT(OLD.BARCODE,"|",OLD.CUSTOMER_CODE,"|",OLD.CALL_NUMBER,"|",OLD.CALL_NUMBER_TYPE,"|",
              OLD.ITEM_AVAIL_STATUS_ID,"|",OLD.COPY_NUMBER,"|",OLD.OWNING_INST_ID ,"|", OLD.COLLECTION_GROUP_ID,"|",
              OLD.CREATED_DATE ,"|", OLD.CREATED_BY , "|",OLD.LAST_UPDATED_DATE,"|", OLD.LAST_UPDATED_BY,"|",
              OLD.USE_RESTRICTIONS,"|", OLD.VOLUME_PART_YEAR,"|",
              OLD.OWNING_INST_ITEM_ID,"|", OLD.IS_DELETED,"|", OLD.CATALOGING_STATUS));
;

CREATE TRIGGER REQUEST_ITEM_T_ADEL AFTER DELETE ON REQUEST_ITEM_T FOR EACH ROW

    INSERT INTO DELETED_RECORDS_T (RECORDS_TABLE, RECORDS_PRIMARY_KEY, DELETED_REPORTED_STATUS, DELETED_DATE, DELETED_BY, RECORDS_LOG)
    VALUES ("request_item_t",""+ OLD.REQUEST_ID, "Not Reported", NOW(), USER()
      ,CONCAT(OLD.ITEM_ID ,"|", OLD.REQUEST_TYPE_ID ,"|", OLD.REQ_EXP_DATE , "|",OLD.CREATED_BY,"|",
              OLD.CREATED_DATE,"|", OLD.LAST_UPDATED_DATE,"|", OLD.PATRON_ID,"|", OLD.STOP_CODE,"|",OLD.REQUESTING_INST_ID,
              "|",OLD.REQUEST_STATUS_ID,"|",OLD.NOTES,"|",OLD.EMAIL_ID
            )
    );
;