/*
-- Query: SELECT * FROM recap.collection_group_t
LIMIT 0, 1000

-- Date: 2016-05-23 16:28
*/
INSERT INTO `recap`.`COLLECTION_GROUP_T` (`COLLECTION_GROUP_ID`,`COLLECTION_GROUP_CODE`,`COLLECTION_GROUP_DESC`,`CREATED_DATE`,`LAST_UPDATED_DATE`) VALUES (1,'Shared','Shared','2016-05-23 01:00:00',NULL);
INSERT INTO `recap`.`COLLECTION_GROUP_T` (`COLLECTION_GROUP_ID`,`COLLECTION_GROUP_CODE`,`COLLECTION_GROUP_DESC`,`CREATED_DATE`,`LAST_UPDATED_DATE`) VALUES (2,'Open','Open','2016-05-23 01:00:00',NULL);
INSERT INTO `recap`.`COLLECTION_GROUP_T` (`COLLECTION_GROUP_ID`,`COLLECTION_GROUP_CODE`,`COLLECTION_GROUP_DESC`,`CREATED_DATE`,`LAST_UPDATED_DATE`) VALUES (3,'Private','Private','2016-05-23 01:00:00',NULL);
INSERT INTO `recap`.`COLLECTION_GROUP_T` (`COLLECTION_GROUP_ID`,`COLLECTION_GROUP_CODE`,`COLLECTION_GROUP_DESC`,`CREATED_DATE`,`LAST_UPDATED_DATE`) VALUES (4,'NA','Not Available','2016-05-23 01:00:00',NULL);