/*
-- Query: select * from recap.institution_t
LIMIT 0, 1000

-- Date: 2016-05-10 18:01
*/
INSERT INTO `recap`.`INSTITUTION_T` (`INSTITUTION_ID`,`INSTITUTION_CODE`,`INSTITUTION_NAME`) VALUES (1,'PUL','Princeton');
INSERT INTO `recap`.`INSTITUTION_T` (`INSTITUTION_ID`,`INSTITUTION_CODE`,`INSTITUTION_NAME`) VALUES (2,'CUL','Columbia');
INSERT INTO `recap`.`INSTITUTION_T` (`INSTITUTION_ID`,`INSTITUTION_CODE`,`INSTITUTION_NAME`) VALUES (3,'NYPL','New York Public Library');
INSERT INTO `recap`.`INSTITUTION_T` (`INSTITUTION_ID`,`INSTITUTION_CODE`,`INSTITUTION_NAME`) VALUES (4,'HTC','HTC Global Services Inc.');
