FROM recapscsb/scsb-base:latest
MAINTAINER HTC ReCAP Support "recap-support@htcindia.com"

#Install Solr
RUN curl www-us.apache.org/dist/lucene/solr/6.5.0/solr-6.5.0.tgz | tar -C /opt/ --extract --gzip

