/*
-- Query: select * from recap.item_status_t
LIMIT 0, 1000

-- Date: 2016-05-10 18:11
*/
INSERT INTO `recap`.`ITEM_STATUS_T` (`ITEM_STATUS_ID`,`STATUS_CODE`,`STATUS_DESC`) VALUES (1,'Available','Available');
INSERT INTO `recap`.`ITEM_STATUS_T` (`ITEM_STATUS_ID`,`STATUS_CODE`,`STATUS_DESC`) VALUES (2,'Not Available','Not Available');
INSERT INTO `recap`.`ITEM_STATUS_T` (`ITEM_STATUS_ID`,`STATUS_CODE`,`STATUS_DESC`) VALUES (3,'Loaned','Loaned');
INSERT INTO `recap`.`ITEM_STATUS_T` (`ITEM_STATUS_ID`,`STATUS_CODE`,`STATUS_DESC`) VALUES (4,'InTransit','InTransit');
INSERT INTO `recap`.`ITEM_STATUS_T` (`ITEM_STATUS_ID`,`STATUS_CODE`,`STATUS_DESC`) VALUES (5,'ShippedToILS','ShippedToILS');
INSERT INTO `recap`.`ITEM_STATUS_T` (`ITEM_STATUS_ID`,`STATUS_CODE`,`STATUS_DESC`) VALUES (6,'ShippedToReCAP','ShippedToReCAP');
